name: monchat

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat
    ports:
      - 89:80
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: chat
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 13306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata:
