version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: chat
    ports:
    - 89:80
  mysql:
    image: mysql:latest
    container_name: BDD
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat
